version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    environment:
      - APP_PORT=$PORT
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - DB_NAME=$DB_NAME
    depends_on:
      - db
    volumes:
      - ./cmd/migrate/migrations:/app/cmd/migrate/migrations


  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASS
      MYSQL_DATABASE: $DB_NAME
      MYSQL_ROOT_HOST: '%'
    volumes:
      - db_data:/var/lib/mysql
      
volumes:
  db_data:
