CREATE TABLE IF NOT EXISTS contacts (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`firstName` VARCHAR(255) NOT NULL,
	`lastName` VARCHAR(255),
	`phone` VARCHAR(255) NOT NULL,
	`address` VARCHAR(255),
	`createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY(id),
    UNIQUE KEY(phone)
);
